# File: prometheus/prometheus.yml

global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'employee-api'
    static_configs:
      - targets: ['employee-api:8000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']